image: node:latest
# Define the stages of the pipeline
stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

# Define the jobs and their steps
build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npx expo start --tunnel

# test:
#   stage: test
#   script:
#     - npm ci
#     - npm run test

production_deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here for the production environment

staging_deploy:
  stage: deploy
  script:
    - echo "Deploying to staging..."
    # Add your deployment commands here for the staging environment
